FROM python:3.10

WORKDIR /home/bandodok/sport_parser
COPY ../../requirements.txt /home/bandodok/sport_parser/requirements.txt
RUN apt update
RUN apt install netcat -y
RUN python -m pip install --upgrade pip
RUN python -m pip install -r requirements.txt