FROM python:3.9

WORKDIR /home/bandodok/sport_parser
COPY ../../requirements.txt /home/bandodok/sport_parser/requirements.txt
RUN python -m pip install --upgrade pip
RUN python -m pip install -r requirements.txt