from datetime import timezone
import datetime

import pytest
from fixtures.db_fixture import update_db
from sport_parser.khl.models import KHLTeams
from sport_parser.khl.view_data.calendar import get_calendar_view
from sport_parser.khl.view_data.match_stats import get_match_stats_view


@pytest.mark.django_db(transaction=True)
def test_get_calendar_view(update_db):
    out = get_calendar_view(21)
    team1_id = KHLTeams.objects.get(name='test1').id
    team2_id = KHLTeams.objects.get(name='test2').id
    team6_id = KHLTeams.objects.get(name='test6').id

    calendar = {
        'finished_matches': {
            15: {'date': datetime.datetime(2017, 8, 20, 21, 0, tzinfo=timezone.utc),
                 'team1_id': team1_id,
                 'team1_image': 'img',
                 'team1_name': 'test1',
                 'team1_score': 4,
                 'team2_id': team2_id,
                 'team2_image': 'img',
                 'team2_name': 'test2',
                 'team2_score': 0,
                 'time': datetime.time(15, 0)},
            17: {'date': datetime.datetime(2017, 8, 23, 21, 0, tzinfo=timezone.utc),
                 'team1_id': team1_id,
                 'team1_image': 'img',
                 'team1_name': 'test1',
                 'team1_score': 8,
                 'team2_id': team6_id,
                 'team2_image': 'img',
                 'team2_name': 'test6',
                 'team2_score': 5,
                 'time': datetime.time(15, 0)},
            18: {'date': datetime.datetime(2017, 8, 24, 21, 0, tzinfo=timezone.utc),
                 'team1_id': team2_id,
                 'team1_image': 'img',
                 'team1_name': 'test2',
                 'team1_score': 8,
                 'team2_id': team6_id,
                 'team2_image': 'img',
                 'team2_name': 'test6',
                 'team2_score': 5,
                 'time': datetime.time(15, 0)},
            19: {'date': datetime.datetime(2017, 8, 25, 21, 0, tzinfo=timezone.utc),
                 'team1_id': team2_id,
                 'team1_image': 'img',
                 'team1_name': 'test2',
                 'team1_score': 8,
                 'team2_id': team1_id,
                 'team2_image': 'img',
                 'team2_name': 'test1',
                 'team2_score': 10,
                 'time': datetime.time(15, 0)},
            20: {'date': datetime.datetime(2017, 8, 26, 21, 0, tzinfo=timezone.utc),
                 'team1_id': team6_id,
                 'team1_image': 'img',
                 'team1_name': 'test6',
                 'team1_score': 8,
                 'team2_id': team2_id,
                 'team2_image': 'img',
                 'team2_name': 'test2',
                 'team2_score': 3,
                 'time': datetime.time(15, 0)},
            22: {'date': datetime.datetime(2017, 8, 28, 21, 0, tzinfo=timezone.utc),
                 'team1_id': team6_id,
                 'team1_image': 'img',
                 'team1_name': 'test6',
                 'team1_score': 3,
                 'team2_id': team1_id,
                 'team2_image': 'img',
                 'team2_name': 'test1',
                 'team2_score': 1,
                 'time': datetime.time(15, 0)}},
        'unfinished_matches': {
            23: {'date': datetime.datetime(2017, 8, 29, 21, 0, tzinfo=timezone.utc),
                 'team1_id': team1_id,
                 'team1_image': 'img',
                 'team1_name': 'test1',
                 'team2_id': team2_id,
                 'team2_image': 'img',
                 'team2_name': 'test2',
                 'time': datetime.time(15, 0)},
            25: {'date': datetime.datetime(2017, 8, 31, 21, 0, tzinfo=timezone.utc),
                 'team1_id': team1_id,
                 'team1_image': 'img',
                 'team1_name': 'test1',
                 'team2_id': team6_id,
                 'team2_image': 'img',
                 'team2_name': 'test6',
                 'time': datetime.time(15, 0)},
            26: {'date': datetime.datetime(2017, 9, 1, 21, 0, tzinfo=timezone.utc),
                 'team1_id': team2_id,
                 'team1_image': 'img',
                 'team1_name': 'test2',
                 'team2_id': team6_id,
                 'team2_image': 'img',
                 'team2_name': 'test6',
                 'time': datetime.time(15, 0)},
            27: {'date': datetime.datetime(2017, 9, 2, 21, 0, tzinfo=timezone.utc),
                 'team1_id': team1_id,
                 'team1_image': 'img',
                 'team1_name': 'test1',
                 'team2_id': team2_id,
                 'team2_image': 'img',
                 'team2_name': 'test2',
                 'time': datetime.time(15, 0)},
            28: {'date': datetime.datetime(2017, 9, 3, 21, 0, tzinfo=timezone.utc),
                 'team1_id': team2_id,
                 'team1_image': 'img',
                 'team1_name': 'test2',
                 'team2_id': team6_id,
                 'team2_image': 'img',
                 'team2_name': 'test6',
                 'time': datetime.time(15, 0)},
            30: {'date': datetime.datetime(2017, 9, 5, 21, 0, tzinfo=timezone.utc),
                 'team1_id': team1_id,
                 'team1_image': 'img',
                 'team1_name': 'test1',
                 'team2_id': team6_id,
                 'team2_image': 'img',
                 'team2_name': 'test6',
                 'time': datetime.time(15, 0)}
        }
    }
    assert out == calendar
