# Generated by Django 3.2.13 on 2022-06-06 08:52

from django.db import migrations, models
import django.db.models.deletion
import json.decoder
import json.encoder


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KHLMatch',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(null=True)),
                ('arena', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('viewers', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('scheduled', 'scheduled'), ('finished', 'finished'), ('postponed', 'postponed'), ('live', 'live'), ('game over', 'game over')], default='scheduled', max_length=9)),
                ('penalties', models.BooleanField(default=False)),
                ('overtime', models.BooleanField(default=False)),
                ('table_data', models.JSONField(decoder=json.decoder.JSONDecoder, encoder=json.encoder.JSONEncoder, null=True)),
                ('chart_data', models.JSONField(decoder=json.decoder.JSONDecoder, encoder=json.encoder.JSONEncoder, null=True)),
                ('bar_data', models.JSONField(decoder=json.decoder.JSONDecoder, encoder=json.encoder.JSONEncoder, null=True)),
                ('live_data', models.JSONField(decoder=json.decoder.JSONDecoder, encoder=json.encoder.JSONEncoder, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KHLSeason',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('external_id', models.IntegerField(null=True)),
                ('table_data', models.JSONField(decoder=json.decoder.JSONDecoder, encoder=json.encoder.JSONEncoder, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KHLTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('arena', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('conference', models.CharField(max_length=100)),
                ('chart_data', models.JSONField(decoder=json.decoder.JSONDecoder, encoder=json.encoder.JSONEncoder, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='khl.khlseason')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KHLProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('g', models.IntegerField(default=0, null=True)),
                ('g_1', models.IntegerField(default=0, null=True)),
                ('g_2', models.IntegerField(default=0, null=True)),
                ('g_3', models.IntegerField(default=0, null=True)),
                ('g_ot', models.IntegerField(default=0, null=True)),
                ('g_b', models.IntegerField(default=0, null=True)),
                ('sh', models.IntegerField(default=0, null=True)),
                ('sog', models.IntegerField(default=0, null=True)),
                ('penalty', models.IntegerField(default=0, null=True)),
                ('faceoff', models.IntegerField(default=0, null=True)),
                ('faceoff_p', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, max_length=100, null=True)),
                ('blocks', models.IntegerField(default=0, null=True)),
                ('hits', models.IntegerField(default=0, null=True)),
                ('fop', models.IntegerField(default=0, null=True)),
                ('time_a', models.TimeField(blank=True, default='00:00:00', max_length=100, null=True)),
                ('vvsh', models.TimeField(blank=True, default='00:00:00', max_length=100, null=True)),
                ('nshv', models.TimeField(blank=True, default='00:00:00', max_length=100, null=True)),
                ('pd', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, max_length=100, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='khl.khlmatch')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='khl.khlseason')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='khl.khlteams')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='khlmatch',
            name='guest_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_matches', to='khl.khlteams'),
        ),
        migrations.AddField(
            model_name='khlmatch',
            name='home_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='khl.khlteams'),
        ),
        migrations.AddField(
            model_name='khlmatch',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='khl.khlseason'),
        ),
        migrations.AddField(
            model_name='khlmatch',
            name='teams',
            field=models.ManyToManyField(related_name='matches', to='khl.KHLTeams'),
        ),
    ]
