# Generated by Django 3.2.6 on 2021-09-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KHLProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('team_id', models.CharField(max_length=100, null=True)),
                ('match_id', models.IntegerField(null=True)),
                ('g', models.IntegerField(null=True)),
                ('sh', models.IntegerField(null=True)),
                ('sog', models.IntegerField(null=True)),
                ('penalty', models.IntegerField(null=True)),
                ('faceoff', models.IntegerField(null=True)),
                ('faceoff_p', models.DecimalField(blank=True, decimal_places=2, max_digits=4, max_length=100, null=True)),
                ('blocks', models.IntegerField(null=True)),
                ('hits', models.IntegerField(null=True)),
                ('fop', models.IntegerField(null=True)),
                ('time_a', models.TimeField(blank=True, max_length=100, null=True)),
                ('vvsh', models.TimeField(blank=True, max_length=100, null=True)),
                ('nshv', models.TimeField(blank=True, max_length=100, null=True)),
                ('pd', models.DecimalField(blank=True, decimal_places=2, max_digits=4, max_length=100, null=True)),
            ],
        ),
    ]
