# Generated by Django 3.2.13 on 2022-06-05 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('khl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khlmatch',
            name='guest_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_matches', to='khl.khlteams'),
        ),
        migrations.AlterField(
            model_name='khlmatch',
            name='home_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='khl.khlteams'),
        ),
    ]
