# Generated by Django 3.2.6 on 2021-09-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khl', '0002_khlteams'),
    ]

    operations = [
        migrations.AddField(
            model_name='khlteams',
            name='season',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='khlprotocol',
            name='match_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='khlprotocol',
            name='team_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
