# Generated by Django 3.2.13 on 2022-06-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khl', '0002_auto_20220605_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khlteams',
            name='img',
            field=models.CharField(max_length=200),
        ),
    ]
