# Generated by Django 3.2.6 on 2021-09-04 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('khl', '0003_auto_20210904_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='KHLMatch',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('match_date', models.DateTimeField()),
                ('season', models.IntegerField()),
                ('arena', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('viewers', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='khlprotocol',
            name='match_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khl.khlmatch'),
        ),
    ]
