# Generated by Django 3.2.6 on 2021-09-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khl', '0004_auto_20210904_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='khlmatch',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='khlmatch',
            name='viewers',
            field=models.IntegerField(default=0),
        ),
    ]
