# Generated by Django 3.2.6 on 2021-10-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khl', '0005_auto_20210930_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khlmatch',
            name='match_date',
        ),
        migrations.AddField(
            model_name='khlmatch',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='khlmatch',
            name='teams',
            field=models.ManyToManyField(to='khl.KHLTeams'),
        ),
        migrations.AddField(
            model_name='khlmatch',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='khlmatch',
            name='arena',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='khlmatch',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='khlmatch',
            name='season',
            field=models.IntegerField(null=True),
        ),
    ]
