# Generated by Django 3.2.6 on 2021-10-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khl', '0006_auto_20211001_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khlmatch',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
