# Generated by Django 3.2.6 on 2021-11-11 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('khl', '0008_alter_khlprotocol_team_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='KHLSeason',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('external_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='khlmatch',
            name='teams',
            field=models.ManyToManyField(related_name='matches', to='khl.KHLTeams'),
        ),
        migrations.AlterField(
            model_name='khlprotocol',
            name='match_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='khl.khlmatch'),
        ),
        migrations.AlterField(
            model_name='khlprotocol',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='khl.khlteams'),
        ),
        migrations.AlterField(
            model_name='khlmatch',
            name='season',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='khl.khlseason'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='khlteams',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='khl.khlseason'),
        ),
    ]
