# Generated by Django 3.2.6 on 2021-11-11 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('khl', '0009_auto_20211111_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khlmatch',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='khl.khlseason'),
        ),
    ]
