# Generated by Django 3.2.6 on 2021-11-11 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khl', '0010_alter_khlmatch_season'),
    ]

    operations = [
        migrations.RenameField(
            model_name='khlmatch',
            old_name='match_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='khlprotocol',
            old_name='match_id',
            new_name='match',
        ),
        migrations.RenameField(
            model_name='khlprotocol',
            old_name='team_id',
            new_name='team',
        ),
    ]
