# Generated by Django 3.2.6 on 2021-11-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khl', '0011_auto_20211111_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='khlprotocol',
            name='g_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='khlprotocol',
            name='g_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='khlprotocol',
            name='g_3',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='khlprotocol',
            name='g_ot',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='khlprotocol',
            name='g_p',
            field=models.IntegerField(null=True),
        ),
    ]
