# Generated by Django 3.2.6 on 2021-11-21 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khl', '0012_auto_20211121_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='khlprotocol',
            old_name='g_p',
            new_name='g_b',
        ),
    ]
