# Generated by Django 3.2.6 on 2021-11-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khl', '0014_auto_20211121_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khlprotocol',
            name='blocks',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='khlprotocol',
            name='faceoff',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='khlprotocol',
            name='faceoff_p',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='khlprotocol',
            name='fop',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='khlprotocol',
            name='g',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='khlprotocol',
            name='g_1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='khlprotocol',
            name='g_2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='khlprotocol',
            name='g_3',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='khlprotocol',
            name='g_b',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='khlprotocol',
            name='g_ot',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='khlprotocol',
            name='hits',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='khlprotocol',
            name='nshv',
            field=models.TimeField(blank=True, default='00:00:00', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='khlprotocol',
            name='pd',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='khlprotocol',
            name='penalty',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='khlprotocol',
            name='sh',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='khlprotocol',
            name='sog',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='khlprotocol',
            name='time_a',
            field=models.TimeField(blank=True, default='00:00:00', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='khlprotocol',
            name='vvsh',
            field=models.TimeField(blank=True, default='00:00:00', max_length=100, null=True),
        ),
    ]
