# Generated by Django 3.2.6 on 2021-12-18 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khl', '0015_auto_20211127_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khlmatch',
            name='time',
        ),
    ]
