# Generated by Django 3.2.6 on 2021-12-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khl', '0016_remove_khlmatch_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khlmatch',
            name='finished',
        ),
        migrations.AddField(
            model_name='khlmatch',
            name='status',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('finished', 'finished'), ('postponed', 'postponed')], default='scheduled', max_length=9),
        ),
    ]
