# Generated by Django 3.2.13 on 2022-06-05 09:50

from django.db import migrations, models
import django.db.models.deletion
import json.decoder
import json.encoder


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NHLMatch',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(null=True)),
                ('arena', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'scheduled'), ('finished', 'finished'), ('postponed', 'postponed'), ('live', 'live'), ('game over', 'game over')], default='scheduled', max_length=9)),
                ('penalties', models.BooleanField(default=False)),
                ('overtime', models.BooleanField(default=False)),
                ('live_data', models.JSONField(decoder=json.decoder.JSONDecoder, encoder=json.encoder.JSONEncoder, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NHLSeason',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('external_id', models.IntegerField(null=True)),
                ('table_data', models.JSONField(decoder=json.decoder.JSONDecoder, encoder=json.encoder.JSONEncoder, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NHLTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('api_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=4)),
                ('img', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('arena', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('conference', models.CharField(max_length=100)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='nhl.nhlseason')),
            ],
        ),
        migrations.CreateModel(
            name='NHLProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('g', models.IntegerField(default=0, null=True)),
                ('g_1', models.IntegerField(default=0, null=True)),
                ('g_2', models.IntegerField(default=0, null=True)),
                ('g_3', models.IntegerField(default=0, null=True)),
                ('g_ot', models.IntegerField(default=0, null=True)),
                ('g_b', models.IntegerField(default=0, null=True)),
                ('sh', models.IntegerField(default=0, null=True)),
                ('sog', models.IntegerField(default=0, null=True)),
                ('penalty', models.IntegerField(default=0, null=True)),
                ('faceoff', models.IntegerField(default=0, null=True)),
                ('faceoff_p', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, max_length=100, null=True)),
                ('blocks', models.IntegerField(default=0, null=True)),
                ('hits', models.IntegerField(default=0, null=True)),
                ('ppp', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, max_length=100, null=True)),
                ('ppg', models.IntegerField(default=0, null=True)),
                ('takeaways', models.IntegerField(default=0, null=True)),
                ('giveaways', models.IntegerField(default=0, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='nhl.nhlmatch')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='nhl.nhlteam')),
            ],
        ),
        migrations.AddField(
            model_name='nhlmatch',
            name='guest_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_matches', to='nhl.nhlteam'),
        ),
        migrations.AddField(
            model_name='nhlmatch',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='nhl.nhlteam'),
        ),
        migrations.AddField(
            model_name='nhlmatch',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='nhl.nhlseason'),
        ),
        migrations.AddField(
            model_name='nhlmatch',
            name='teams',
            field=models.ManyToManyField(related_name='matches', to='nhl.NHLTeam'),
        ),
    ]
