# Generated by Django 3.2.6 on 2021-12-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0002_alter_nhlteam_api_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhlprotocol',
            name='faceoff_p',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nhlprotocol',
            name='ppp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, max_length=100, null=True),
        ),
    ]
