# Generated by Django 3.2.13 on 2022-06-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0002_auto_20220605_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhlmatch',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
