# Generated by Django 3.2.6 on 2021-12-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0003_auto_20211215_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhlprotocol',
            name='faceoff',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='nhlprotocol',
            name='sh',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
