# Generated by Django 3.2.13 on 2022-06-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0003_nhlmatch_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhlmatch',
            name='viewers',
            field=models.IntegerField(default=0),
        ),
    ]
