# Generated by Django 3.2.13 on 2022-06-05 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0004_nhlmatch_viewers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nhlteam',
            name='abbreviation',
        ),
        migrations.RemoveField(
            model_name='nhlteam',
            name='api_id',
        ),
        migrations.RemoveField(
            model_name='nhlteam',
            name='short_name',
        ),
    ]
