# Generated by Django 3.2.6 on 2021-12-18 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0005_auto_20211218_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nhlmatch',
            old_name='datetime',
            new_name='date',
        ),
    ]
