# Generated by Django 3.2.6 on 2021-12-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0006_rename_datetime_nhlmatch_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhlmatch',
            name='postponed',
            field=models.BooleanField(default=False),
        ),
    ]
