# Generated by Django 3.2.6 on 2021-12-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0008_auto_20211221_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhlteam',
            name='img',
            field=models.CharField(max_length=200),
        ),
    ]
