# Generated by Django 3.2.6 on 2022-03-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0010_nhlseason_table_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhlmatch',
            name='status',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('finished', 'finished'), ('postponed', 'postponed'), ('live', 'live')], default='scheduled', max_length=9),
        ),
    ]
