# Generated by Django 3.2.6 on 2022-04-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhl', '0012_nhlmatch_live_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhlmatch',
            name='status',
            field=models.CharField(choices=[('scheduled', 'scheduled'), ('finished', 'finished'), ('postponed', 'postponed'), ('live', 'live'), ('game over', 'game over')], default='scheduled', max_length=9),
        ),
    ]
