# Generated by Django 3.2.6 on 2022-03-27 15:39

from django.db import migrations, models
import json.decoder
import json.encoder


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveMatches',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('league', models.CharField(max_length=100)),
                ('match_id', models.IntegerField()),
                ('match_status', models.CharField(max_length=100)),
                ('match_data', models.JSONField(decoder=json.decoder.JSONDecoder, encoder=json.encoder.JSONEncoder, null=True)),
            ],
        ),
    ]
