# Generated by Django 3.2.6 on 2022-03-28 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220327_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livematches',
            name='match_status',
        ),
    ]
