# Generated by Django 3.2.6 on 2022-04-03 13:25

from django.db import migrations, models
import json.decoder
import json.encoder


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_livematches_match_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livematches',
            name='match_data',
            field=models.JSONField(decoder=json.decoder.JSONDecoder, default={'data': {'row_guest': '', 'row_home': ''}, 'match_status': 'матч скоро начнется', 'team_1_score': '-', 'team_2_score': '-'}, encoder=json.encoder.JSONEncoder, null=True),
        ),
    ]
