# Generated by Django 3.2.6 on 2022-04-07 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_livematches_match_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livematches',
            name='match_data',
        ),
    ]
